artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  dataset_name: conll2003

tokenizer_preparation:
  root_dir: artifacts/tokenizer_preparation
  data_path: artifacts/data_ingestion/conll2003

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/conll2003
  tokenizer_path: artifacts/tokenizer_preparation/tokenizer.pickle

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/conll2003

model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/conll2003
  model_weights_path: artifacts/model_trainer/model_weights
