artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  dataset_name: conll2003

tokenizer_preparation:
  root_dir: artifacts/tokenizer_preparation
  data_path: artifacts/data_ingestion/conll2003

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data.pickle
  tokenizer_path: artifacts/tokenizer_preparation/tokenizer.pickle
  updated_data_path: artifacts/data_transformation/data.pickle
