stages:
  data_ingestion:
    cmd: python src/named_entity_recognition/pipeline/stage_01_data_ingestion.py
    deps:
      - config/config.yaml
      - src/named_entity_recognition/pipeline/stage_01_data_ingestion.py
    outs:
      - artifacts/data_ingestion/conll2003
  embedding_preparation:
    cmd: python src/named_entity_recognition/pipeline/stage_02_embedding_preparation.py
    deps:
      - config/config.yaml
      - src/named_entity_recognition/pipeline/stage_02_embedding_preparation.py
    params:
      - EMBEDDING_DIM
    outs:
      - artifacts/embedding_preparation/glove.6B
      - artifacts/embedding_preparation/tokenizer.pickle
      - artifacts/embedding_preparation/embedding_weights.pickle
  data_transformation:
    cmd: python src/named_entity_recognition/pipeline/stage_03_data_transformation.py
    deps:
      - config/config.yaml
      - src/named_entity_recognition/pipeline/stage_03_data_transformation.py
      - artifacts/embedding_preparation/tokenizer.pickle
    outs:
      - artifacts/data_transformation/conll2003
  model_training:
    cmd: python src/named_entity_recognition/pipeline/stage_04_model_trainer.py
    deps:
      - config/config.yaml
      - src/named_entity_recognition/pipeline/stage_04_model_trainer.py
      - artifacts/data_transformation/conll2003
    params:
      - NUM_ENCODER_LAYERS
      - NUM_HEADS
      - EMBEDDING_DIM
      - FULLY_CONNECTED_DIM
      - MAX_POSITIONAL_ENCODING_LENGTH
      - EPOCHS
      - BATCH_SIZE
    outs:
      - artifacts/model_trainer/model.keras
  model_evaluation:
    cmd: python src/named_entity_recognition/pipeline/stage_05_model_evaluation.py
    deps:
      - config/config.yaml
      - src/named_entity_recognition/pipeline/stage_05_model_evaluation.py
      - artifacts/data_transformation/conll2003
      - artifacts/model_trainer/model.keras
    params:
      - BATCH_SIZE
    metrics:
      - artifacts\model_evaluation\scores.json:
          cache: False
