MAX_SEQUENCE_LENGTH: 100
LABEL_ALL_TOKENS: True
NUM_ENCODER_LAYERS: 2
NUM_TAGS: 9
VOCAB_SIZE: 339300
EMBEDDING_DIM: 50
FULLY_CONNECTED_DIM: 50
NUM_HEADS: 2
MAX_POSITIONAL_ENCODING_LENGTH: 150
EPOCHS: 1
BATCH_SIZE: 64
