MAX_SEQUENCE_LENGTH: 100
LABEL_ALL_TOKENS: True
NUM_ENCODER_LAYERS: 4
NUM_TAGS: 9
VOCAB_SIZE: 339300
EMBEDDING_DIM: 100
FULLY_CONNECTED_DIM: 100
NUM_HEADS: 4
MAX_POSITIONAL_ENCODING_LENGTH: 150
EPOCHS: 20
BATCH_SIZE: 64
