MAX_SEQUENCE_LENGTH: 100
LABEL_ALL_TOKENS: True
NUM_ENCODER_LAYERS: 2
NUM_TAGS: 9
VOCAB_SIZE: 17700
EMBEDDING_DIM: 100
FULLY_CONNECTED_DIM: 100
NUM_HEADS: 5
MAX_POSITIONAL_ENCODING_LENGTH: 150
EPOCHS: 10
BATCH_SIZE: 64
