MAX_SEQUENCE_LENGTH: 100
LABEL_ALL_TOKENS: True
NUM_ENCODER_LAYERS: 5
NUM_TAGS: 10
VOCAB_SIZE: 17700
EMBEDDING_DIM: 64
FULLY_CONNECTED_DIM: 64
NUM_HEADS: 5
MAX_POSITIONAL_ENCODING_LENGTH: 150
EPOCHS: 10
BATCH_SIZE: 64
